version: "3"

includes:
  app:
    taskfile: ../Taskfile.yaml

tasks:
  build-app:
    desc: "Builds all components of the Library Application"
    cmds:
      - task: bookinfo:build
      - task: gateway:build
      - task: renting:build
      - task: user-management:build

  build-service:
    cmd: task $SERVICE:build

  check-pull-request:
    desc: "Run Pull Request Checks"
    cmds:
      - task: lint
      - task: build-app
      - task: validate-helm-charts
      - task: check-api-compatibility

  deploy-app:
    desc: "TODO"

  detect-changed-services:
    desc: "Determine which services have changes"
    vars:
      BASE_SHA:
        sh: git ls-remote -q | grep refs/heads/main | awk '{print $1}' | xargs git rev-parse --short
      HEAD_SHA:
        sh: git rev-parse HEAD
    cmds:
      - ./scripts/detect_changed_services.sh "{{.BASE_SHA}}" "{{.HEAD_SHA}}" bookinfo gateway renting user-management

  open-api-diff:
    desc: "Run openapi-diff"
    vars:
      API_SPEC_FILE: "default.yml"
    cmd: |
      curl -H "Authorization: token {{.GH_TOKEN}}" -sL https://raw.githubusercontent.com/fbrandes/library-project/refs/heads/main/api/spec/{{.API_SPEC_FILE}} -o old.yaml
      cp api/spec/{{.API_SPEC_FILE}} new.yaml
      docker run --rm -v ${pwd}:/workspace -w /workspace openapitools/openapi-diff:latest -fail-on-incompatible old.yaml new.yaml
