version: "3"

tasks:
  deploy-app:
    desc: "TODO"

  detect-changed-services:
    desc: "Determine which services have changes"
    vars:
      BASE_SHA:
        sh: git ls-remote -q | grep refs/heads/main | awk '{print $1}' | xargs git rev-parse --short
      HEAD_SHA:
        sh: git rev-parse HEAD
    cmds:
      - ./scripts/detect_changed_services.sh "{{.BASE_SHA}}" "{{.HEAD_SHA}}" bookinfo gateway renting user-management

  open-api-diff:
    desc: "Run openapi-diff"
    dir: api/spec
    cmd: |
      curl -sL https://raw.githubusercontent.com/fbrandes/library-project/refs/heads/main/api/spec/{{.API_SPEC_FILE}} -o old-{{.API_SPEC_FILE}}
      cp {{.API_SPEC_FILE}} new-{{.API_SPEC_FILE}}
      docker run --rm -v $(pwd):/workspace -w /workspace openapitools/openapi-diff:latest -fail-on-incompatible old-{{.API_SPEC_FILE}} new-{{.API_SPEC_FILE}}
