spring:
  application:
    name: bookinfo
  mongodb:
    representation:
      uuid: standard
    database: bookinfo
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,info
