version: "3"

tasks:
    build-backend-image:
        desc: "Builds the User Management backend Docker image"
        dir: ./backend
        vars:
            APP_VERSION:
                sh: cat package.json | jq -r '.version'
            IMAGE_VERSION: "{{.APP_VERSION| default latest }}"
        cmd: docker build -t fbrandes-library/user-management-frontend:${APP_VERSION} .
    build-frontend-image:
        desc: "Builds the User Management frontend Docker image"
        dir: ./frontend
        vars:
            APP_VERSION:
                sh: cat package.json | jq -r '.version'
            IMAGE_VERSION: "{{.APP_VERSION| default latest }}"
        cmd: docker build -t fbrandes-library/user-management-backend:${APP_VERSION} .
